/* !---- DO NOT EDIT: This file autogenerated by com/sun/gluegen/JavaEmitter.java on Tue Feb 09 18:20:26 CET 2010 ----! */


package com.jogamp.opencl.demos.julia3d.structs;


class Camera64 extends Camera {

  private final Vec orig;
  private final Vec target;
  private final Vec dir;
  private final Vec x;
  private final Vec y;

  public static int size() {
    return 60;
  }

  Camera64(java.nio.ByteBuffer buf) {
    super(buf);
    orig = Vec.create(accessor.slice(0, 12));
    target = Vec.create(accessor.slice(12, 12));
    dir = Vec.create(accessor.slice(24, 12));
    x = Vec.create(accessor.slice(36, 12));
    y = Vec.create(accessor.slice(48, 12));
  }


  public Vec getOrig() {
    return orig;
  }

  public Vec getTarget() {
    return target;
  }

  public Vec getDir() {
    return dir;
  }

  public Vec getX() {
    return x;
  }

  public Vec getY() {
    return y;
  }
}
