/* !---- DO NOT EDIT: This file autogenerated by com/sun/gluegen/JavaEmitter.java on Tue Feb 09 18:20:26 CET 2010 ----! */


package com.jogamp.opencl.demos.julia3d.structs;

import com.jogamp.common.nio.*;


public class Camera {
  private final Vec orig;
  private final Vec target;
  private final Vec dir;
  private final Vec x;
  private final Vec y;
  
  public Camera(java.nio.ByteBuffer buf) {
    StructAccessor accessor = new StructAccessor(buf);
    orig    = new Vec(accessor.slice(0 * Vec.size(), Vec.size())); 
    target  = new Vec(accessor.slice(1 * Vec.size(), Vec.size()));
    dir     = new Vec(accessor.slice(2 * Vec.size(), Vec.size()));
    x       = new Vec(accessor.slice(3 * Vec.size(), Vec.size()));
    y       = new Vec(accessor.slice(4 * Vec.size(), Vec.size()));
  }

  public static int size() {
    return Vec.size() * 5;
  }

  public Vec getOrig() {
    return orig;
  }

  public Vec getTarget() {
    return target;
  }

  public Vec getDir() {
    return dir;
  }

  public Vec getX() {
    return x;
  }

  public Vec getY() {
    return y;
  }
  
  public String toString() {
    return "{\n"
      + "\torigin: " + getOrig() + ",\n" 
      + "\ttarget: " + getTarget() + ",\n" 
      + "\tdir:    " + getDir() + ",\n" 
      + "\tx:      " + getX() + ",\n" 
      + "\ty:      " + getY() + ",\n}"; 
  }
  
}
