/* !---- DO NOT EDIT: This file autogenerated by com/sun/gluegen/JavaEmitter.java on Tue Feb 09 18:20:26 CET 2010 ----! */


package com.jogamp.opencl.demos.julia3d.structs;


class Camera32 extends Camera {

  public static int size() {
    return 76;
  }

  Camera32(java.nio.ByteBuffer buf) {
    super(buf);
  }


  public Vec getOrig() {
    return Vec.create(accessor.slice(0, 12));
  }

  public Vec getTarget() {
    return Vec.create(accessor.slice(16, 12));
  }

  public Vec getDir() {
    return Vec.create(accessor.slice(32, 12));
  }

  public Vec getX() {
    return Vec.create(accessor.slice(48, 12));
  }

  public Vec getY() {
    return Vec.create(accessor.slice(64, 12));
  }
}
