/* !---- DO NOT EDIT: This file autogenerated by com/sun/gluegen/JavaEmitter.java on Tue Feb 09 18:20:26 CET 2010 ----! */


package com.jogamp.opencl.demos.julia3d.structs;


import com.jogamp.common.nio.*;


public abstract class Vec {

  StructAccessor accessor;

  public static int size() {
//    if (CPU.is32Bit()) {
//      return Vec32.size();
//    } else {
      return Vec64.size();
//    }
  }

  public static Vec create() {
    return create(Buffers.newDirectByteBuffer(size()));
  }

  public static Vec create(java.nio.ByteBuffer buf) {
//    if (CPU.is32Bit()) {
//      return new Vec32(buf);
//    } else {
      return new Vec64(buf);
//    }
  }

  Vec(java.nio.ByteBuffer buf) {
    accessor = new StructAccessor(buf);
  }

  public java.nio.ByteBuffer getBuffer() {
    return accessor.getBuffer();
  }

  public abstract Vec setX(float val);

  public abstract float getX();

  public abstract Vec setY(float val);

  public abstract float getY();

  public abstract Vec setZ(float val);

  public abstract float getZ();
}
