/* !---- DO NOT EDIT: This file autogenerated by com/sun/gluegen/JavaEmitter.java on Tue Feb 09 18:20:26 CET 2010 ----! */


package com.jogamp.opencl.demos.julia3d.structs;


import com.jogamp.common.nio.*;


public class Vec {

  public static final Vec UP = new Vec(Buffers.newDirectByteBuffer(size())).setX(0).setY(1).setZ(0);
  
  public static int size() {
    return 3 * (Float.SIZE / Byte.SIZE);
  }

  private StructAccessor accessor;

  public Vec() {
    this(Buffers.newDirectByteBuffer(size()));
  }

  public java.nio.ByteBuffer getBuffer() {
    return accessor.getBuffer();
  }

  public Vec(java.nio.ByteBuffer buf) {
    accessor = new StructAccessor(buf);
  }

  public Vec setX(float val) {
    accessor.setFloatAt(0, val);
    return this;
  }

  public float getX() {
    return accessor.getFloatAt(0);
  }

  public Vec setY(float val) {
    accessor.setFloatAt(4, val);
    return this;
  }

  public float getY() {
    return accessor.getFloatAt(4);
  }

  public Vec setZ(float val) {
    accessor.setFloatAt(8, val);
    return this;
  }

  public float getZ() {
    return accessor.getFloatAt(8);
  }
  

  public String toString() {
    return "{ " + getX() + ", " + getY() + ", " + getZ() + " }";
  }
}


